# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmd.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmd.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\tcmd.proto\"8\n\x03\x43md\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1a\n\x07pid_cmd\x18\x02 \x01(\x0b\x32\x07.PIDCmdH\x00\x42\t\n\x07\x63ontent\"\xa5\x01\n\x06PIDCmd\x12\x12\n\nenable_pid\x18\x01 \x01(\x08\x12\n\n\x02kp\x18\x02 \x01(\x02\x12\n\n\x02ki\x18\x03 \x01(\x02\x12\n\n\x02kd\x18\x04 \x01(\x02\x12\x1a\n\x12\x65nable_anti_windup\x18\x05 \x01(\x08\x12\x0b\n\x03min\x18\x06 \x01(\x02\x12\x0b\n\x03max\x18\x07 \x01(\x02\x12\n\n\x02ts\x18\x08 \x01(\x02\x12\t\n\x01w\x18\t \x01(\x02\x12\t\n\x01u\x18\n \x01(\x02\x12\x0b\n\x03tau\x18\x0b \x01(\x02\x62\x06proto3'
)




_CMD = _descriptor.Descriptor(
  name='Cmd',
  full_name='Cmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Cmd.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid_cmd', full_name='Cmd.pid_cmd', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='Cmd.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=13,
  serialized_end=69,
)


_PIDCMD = _descriptor.Descriptor(
  name='PIDCmd',
  full_name='PIDCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable_pid', full_name='PIDCmd.enable_pid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kp', full_name='PIDCmd.kp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ki', full_name='PIDCmd.ki', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kd', full_name='PIDCmd.kd', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable_anti_windup', full_name='PIDCmd.enable_anti_windup', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min', full_name='PIDCmd.min', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max', full_name='PIDCmd.max', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ts', full_name='PIDCmd.ts', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='PIDCmd.w', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='u', full_name='PIDCmd.u', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tau', full_name='PIDCmd.tau', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=237,
)

_CMD.fields_by_name['pid_cmd'].message_type = _PIDCMD
_CMD.oneofs_by_name['content'].fields.append(
  _CMD.fields_by_name['pid_cmd'])
_CMD.fields_by_name['pid_cmd'].containing_oneof = _CMD.oneofs_by_name['content']
DESCRIPTOR.message_types_by_name['Cmd'] = _CMD
DESCRIPTOR.message_types_by_name['PIDCmd'] = _PIDCMD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cmd = _reflection.GeneratedProtocolMessageType('Cmd', (_message.Message,), {
  'DESCRIPTOR' : _CMD,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:Cmd)
  })
_sym_db.RegisterMessage(Cmd)

PIDCmd = _reflection.GeneratedProtocolMessageType('PIDCmd', (_message.Message,), {
  'DESCRIPTOR' : _PIDCMD,
  '__module__' : 'cmd_pb2'
  # @@protoc_insertion_point(class_scope:PIDCmd)
  })
_sym_db.RegisterMessage(PIDCmd)


# @@protoc_insertion_point(module_scope)
