/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "cmd.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Cmd, Cmd, AUTO)


PB_BIND(PIDCmd, PIDCmd, AUTO)



