/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "info.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Info, Info, AUTO)


PB_BIND(PIDInfo, PIDInfo, AUTO)



